/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form;

import com.mycompany.domainModel.RankKhachHang;
import com.mycompany.service.impl.RankServiceImpl;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PTS
 */
public class JDialogRankKhachHang extends javax.swing.JDialog {

    /**
     * Creates new form JDialogRankKhachHang
     */
    private DefaultTableModel dtmRank = new DefaultTableModel();
    private RankServiceImpl rankServiceImpl = new RankServiceImpl();
    private List<RankKhachHang> listRank = rankServiceImpl.getAll();

    public JDialogRankKhachHang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String header[] = {"Mã Rank", "Tên Rank", "Tiền ban đầu", "Tiền kết thúc", "Khuyễn mãi", "Trạng Thái"};
        tbXepLoai.setModel(dtmRank);
        dtmRank.setColumnIdentifiers(header);
        showDataTable(listRank);
        radioActive.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaRank = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtTenRank = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSotienBatDau = new javax.swing.JTextField();
        txtSoTienKThuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoPhanTramGiam = new javax.swing.JTextField();
        radioActive = new javax.swing.JRadioButton();
        radioUnactive = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbXepLoai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("XẾP LOẠI KHÁCH HÀNG");

        jLabel2.setText("Mã Rank :");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Rank:");

        jLabel5.setText("Số tiền bắt đầu :");

        jLabel6.setText("Số tiền kết thúc :");

        jLabel3.setText("Số phần trăm giảm :");

        radioActive.setText("Active");

        radioUnactive.setText("Unactive");

        jLabel7.setText("Trạng thái :");

        tbXepLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbXepLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXepLoaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbXepLoai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenRank, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaRank, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoTienKThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSotienBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radioActive)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(radioUnactive))
                                            .addComponent(txtSoPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel6))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnUpdate))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSotienBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSoTienKThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSoPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(radioActive))
                            .addComponent(radioUnactive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnAdd)
                        .addGap(28, 28, 28)
                        .addComponent(btnDelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int index = tbXepLoai.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "?");
        } else {
            if (txtMaRank.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã không được để trống");
                return;
            }
            if (txtTenRank.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã không được để trống");
                return;
            }
            if (!txtTenRank.getText().matches("[^\\s][A-Za-zÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝàáâãèéêìíòóôõùúýĂăĐđĨĩŨũƠơƯưẠ-ỹ ]+[^\\s]")) {
                JOptionPane.showMessageDialog(this, "Tên không đúng định dạng");
                return;
            } else {
                int ma = Integer.valueOf(txtMaRank.getText());
                RankKhachHang rankKhachHang = newRank();

                JOptionPane.showMessageDialog(this, rankServiceImpl.update(rankKhachHang, ma));
                listRank = rankServiceImpl.getAll();
                showDataTable(listRank);
                btnClearActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    public boolean kiemTraTrungMaLoai() {
        listRank = rankServiceImpl.getAll();
        for (RankKhachHang l : listRank) {
            if (txtMaRank.getText().equalsIgnoreCase((l.getMaRank()))) {
                return false;
            }
        }
        return true;
    }

    private RankKhachHang newRank() {
        RankKhachHang rankKhachHang = new RankKhachHang();
        rankKhachHang.setMaRank(txtMaRank.getText());
        rankKhachHang.setTenRank(txtTenRank.getText());
        rankKhachHang.setSoTienBatDau(BigDecimal.valueOf(Double.valueOf(txtSotienBatDau.getText())));
        rankKhachHang.setSoTienKetThuc(BigDecimal.valueOf(Double.valueOf(txtSoTienKThuc.getText())));
        rankKhachHang.setKhuyenMaiRank(Integer.valueOf(txtSoPhanTramGiam.getText()));
        if (radioActive.isSelected()) {
            rankKhachHang.setTrangThai(0);
        } else {
            rankKhachHang.setTrangThai(1);
        }
        return rankKhachHang;
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!txtMaRank.getText().isEmpty()) {
            RankKhachHang loai = newRank();
            if (!(kiemTraTrungMaLoai())) {
                JOptionPane.showMessageDialog(this, "Mã đã tồn tại");
                return;

            }
            if (txtMaRank.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã không được để trống");
                return;
            }
            if (txtTenRank.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã không được để trống");
                return;
            }
            if (!txtTenRank.getText().matches("[^\\s][A-Za-zÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝàáâãèéêìíòóôõùúýĂăĐđĨĩŨũƠơƯưẠ-ỹ ]+[^\\s]")) {
                JOptionPane.showMessageDialog(this, "Tên không đúng định dạng");
                return;
            } else {
                JOptionPane.showMessageDialog(this, rankServiceImpl.add(loai));
                listRank = rankServiceImpl.getAll();
                showDataTable(listRank);
                btnClearActionPerformed(evt);
            }
        } else {
            JOptionPane.showMessageDialog(this, "clear trước khi add");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int index = tbXepLoai.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "?");
        } else {
            int ma = Integer.valueOf(txtMaRank.getText());
            JOptionPane.showMessageDialog(this, rankServiceImpl.remove(ma));
            listRank = rankServiceImpl.getAll();
            showDataTable(listRank);
            btnClearActionPerformed(evt);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaRank.setText("");
        txtSoPhanTramGiam.setText("");
        txtSoTienKThuc.setText("");
        txtSotienBatDau.setText("");
        txtTenRank.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tbXepLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXepLoaiMouseClicked
        // TODO add your handling code here:
        RankKhachHang rankKhachHang = listRank.get(tbXepLoai.getSelectedRow());
        txtMaRank.setText(String.valueOf(rankKhachHang.getMaRank()));
        txtTenRank.setText(rankKhachHang.getTenRank());
        txtSoTienKThuc.setText(String.valueOf(rankKhachHang.getSoTienKetThuc()));
        txtSotienBatDau.setText((String.valueOf(rankKhachHang.getSoTienBatDau())));
        txtSoPhanTramGiam.setText(String.valueOf(rankKhachHang.getKhuyenMaiRank()));
    }//GEN-LAST:event_tbXepLoaiMouseClicked
    private void showDataTable(List<RankKhachHang> listRank) {
        dtmRank.setRowCount(0);
        for (int i = 0; i < listRank.size(); i++) {
            dtmRank.addRow(new Object[]{listRank.get(i).getMaRank(), listRank.get(i).getTenRank(), listRank.get(i).getSoTienBatDau(),
                listRank.get(i).getSoTienKetThuc(), listRank.get(i).getKhuyenMaiRank(), listRank.get(i).getTrangThai()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRankKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRankKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRankKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRankKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogRankKhachHang dialog = new JDialogRankKhachHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioActive;
    private javax.swing.JRadioButton radioUnactive;
    private javax.swing.JTable tbXepLoai;
    private javax.swing.JTextField txtMaRank;
    private javax.swing.JTextField txtSoPhanTramGiam;
    private javax.swing.JTextField txtSoTienKThuc;
    private javax.swing.JTextField txtSotienBatDau;
    private javax.swing.JTextField txtTenRank;
    // End of variables declaration//GEN-END:variables
}
